name: URBANFLEX

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    name: ops-flex-module
    runs-on: ubuntu-latest
    steps:
      # Step 1: Set up SSH
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 2: Add SSH Host Key
      - name: Add SSH Host Key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p 22 ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      # Step 3: Run Deployment Commands on the Server
      - name: Pull Changes and Run Deployment Commands
        run: |
          ssh -p 22 ${{ secrets.USERNAME }}@${{ secrets.HOST }} << 'EOF'
            cd ${{ secrets.DIR }}

            # Fetch the latest changes from the remote repository.
            git pull https://${{ secrets.PULL_TOKEN }}@github.com/${{ secrets.REPO }}

            # Run deployment commands
            composer install --no-interaction --prefer-dist --optimize-autoloader
            php artisan migrate --force
            php artisan optimize
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache

            echo "Deployment complete!"
          EOF

      # Step 4: Notify on failure
      - name: Notify on Failure
        if: failure()
        run: echo "Deployment failed. Please check the logs for details."

      # Step 5: Notify on Success
      - name: Notify on Success
        if: success()
        run: echo "Deployment succeeded! Your application has been deployed successfully."
